### ISSUE TITLE
ShapeSpec object is not subscriptable

### ISSUE THREAD

**Issue by epistimi22** [saksham-s/SparseDet#1]
hi, I'm running your codes, and an error occurs.
model.py line 118, _output_shape = {'p2': ShapeSpec(channels=2*output_shape['p2'][0], height=None, width=None, stride=4), \_
We know that output_shape['p2'] is a ShapeSpec class and it has four attributes, so, if you want to get its value of 'channels', it should be output_shape['p2'].channels rather than output_shape['p2'][0].
Anyway, I'm not sure whether I'm right.
Maybe you can check it, thanks for your work!

**Comment by saksham-s** [comment]
Hi, I do not face this error, have you used the same versions as mentioned in the repo. Also attaching my current environment pip list which helped me reproduce the repos results in case that helps.
[requirements.txt](https://github.com/user-attachments/files/16194608/requirements.txt)
